theme: minima
title: mint mayhem
author: mintmayhem6
email: stef@mintmayhem.com
description: > # this means to ignore newlines until "baseurl:"
 Let's get those pull requests!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

